			<div class="admin__dashboard--nav">
				<p class="text-center"><a href="/admin/"><img src="<?=PATH?>assets/images/logo-csa-white.png" alt="Logotipo do Canal Salto Alto" class="logo" /></a></p>

				<nav>
					<ul>
						<li>
							<a href="/admin/posts">Posts</a>
							<ul>
								<li><a href="/admin/posts/">Todos os Posts</a></li>
								<li><a href="/admin/posts/new">Novo Post</a></li>
							</ul>
						</li>
						<li>
							<a href="/admin/notices">Avisos</a>
							<ul>
								<li><a href="/admin/notices">Todos os avisos</a></li>
								<li><a href="/admin/notices/new">Novo Aviso</a></li>
							</ul>
						</li>
						<li>
							<a href="/admin/contents">Conteúdos</a>
							<ul>
								<li><a href="/admin/contents">Todos os Conteúdos</a></li>
								<li><a href="/admin/contents/new">Novo Conteúdo</a></li>
							</ul>
						</li>
						<li>
							<a href="/admin/clubs">Clubes</a>
							<ul>
								<li><a href="/admin/clubs">Todos os Clubes</a></li>
								<li><a href="/admin/clubs/new">Novo Clube</a></li>
							</ul>
						</li>
						<li>
							<a href="/admin/events">Eventos</a>
							<ul>
								<li><a href="/admin/events">Todos os Eventos</a></li>
								<li><a href="/admin/events/new">Novo Evento</a></li>
							</ul>
						</li>
						<li>
							<a href="/admin/publis">Publi</a>
							<ul>
								<li><a href="/admin/publis">Todas as publis</a></li>
								<li><a href="/admin/publis/new">Nova Publi</a></li>
								<li><a href="/admin/publis/approves">Aprovações pendentes</a></li>
							</ul>
						</li>
						<li>
							<a href="/admin/members">Membros</a>
							<ul>
								<li><a href="/admin/members/">Todos os Membros</a></li>
								<li><a href="/admin/members/active">Membros Ativos</a></li>
								<li><a href="/admin/members/inactive">Membros Inativos</a></li>
								<!-- <li><a href="/admin/  /"></a></li> -->
							</ul>
						</li>
						<li>
							<a href="/admin/companies">Empresas</a>
							<ul>
								<li><a href="/admin/companies/">Todas as Empresas</a></li>
								<li><a href="/admin/companies/new">Nova empresa</a></li>
								<li><a href="/admin/companies/approves">Aprovações pendentes</a></li>
							</ul>
						</li>

						<li>
							<a href="/admin/logout">Sair</a>
						</li>
					</ul>
				</nav>	


				
			</div>