<div class="admin__dashboard--nav">
				<p class="text-center"><a href="/admin/"><img src="<?=PATH?>assets/images/logo-csa.png" alt="Logotipo do Canal Salto Alto" class="logo" /></a></p>

				<a href="javascript:void(0)" onclick="$('nav').toggle('fast')"><img src="<?=PATH?>assets/images/icone-menu.svg" alt="" class="admin__dashboard--nav--mobilebtn" /></a>
				<nav>
					<ul>
						<li>
							<a href="/admin/banners"><i class="text-primary fa-solid fa-images"></i> Banners</a>
							<ul>
								<li><a href="/admin/banners">Todos os Banners</a></li>
								<li><a href="/admin/banners/new">Novo Banner</a></li>
							</ul>
						</li>
						<li>
							<a href="/admin/posts"><i class="text-primary fa-solid fa-list-ul"></i> Posts</a>
							<ul>
								<li><a href="/admin/posts/">Todos os Posts</a></li>
								<li><a href="/admin/posts/new">Novo Post</a></li>
							</ul>
						</li>
						<!-- <li>
							<a href="/admin/notices">Avisos</a>
							<ul>
								<li><a href="/admin/notices">Todos os avisos</a></li>
								<li><a href="/admin/notices/new">Novo Aviso</a></li>
							</ul>
						</li> -->
						<li>
							<a href="/admin/contents"><i class="text-primary fa-solid fa-hashtag"></i> Conteúdos</a>
							<ul>
								<li><a href="/admin/contents">Todos os Conteúdos</a></li>
								<li><a href="/admin/contents/new">Novo Conteúdo</a></li>
							</ul>
						</li>
						<li>
							<a href="/admin/clubs"><i class="text-primary fa-solid fa-tag"></i> Clubes</a>
							<ul>
								<li><a href="/admin/clubs">Todos os Clubes</a></li>
								<li><a href="/admin/clubs/new">Novo Clube</a></li>
							</ul>
						</li>
						<li>
							<a href="/admin/events"><i class="text-primary fa-solid fa-video"></i> Eventos</a>
							<ul>
								<li><a href="/admin/events">Todos os Eventos</a></li>
								<li><a href="/admin/events/new">Novo Evento</a></li>
							</ul>
						</li>
						<li>
							<a href="/admin/tutorials"><i class="text-primary fa-solid fa-shoe-prints"></i> Tutoriais (Comece Aqui)</a>
							<ul>
								<li><a href="/admin/tutorials">Todos os Tutoriais</a></li>
								<li><a href="/admin/tutorials/new">Novo Tutorial</a></li>
							</ul>
						</li>
						<li>
							<a href="/admin/publis"><i class="text-primary fa-solid fa-microphone"></i> Publi</a>
							<ul>
								<li><a href="/admin/publis">Todas as publis</a></li>
								<li><a href="/admin/publis/new">Nova Publi</a></li>
								<li><a href="/admin/publis/approves">Aprovações pendentes</a></li>
							</ul>
						</li>
						<li>
							<a href="/admin/members"><i class="text-primary fa-solid fa-users"></i> Membros</a>
							<ul>
								<li><a href="/admin/members/">Todos os Membros</a></li>
								<li><a href="/admin/members/active">Membros Ativos</a></li>
								<li><a href="/admin/members/inactive">Membros Inativos</a></li>
								<!-- <li><a href="/admin/  /"></a></li> -->
							</ul>
						</li>
						<li>
							<a href="/admin/companies"><i class="text-primary fa-solid fa-briefcase"></i> Empresas</a>
							<ul>
								<li><a href="/admin/companies/">Todas as Empresas</a></li>
								<li><a href="/admin/companies/new">Nova empresa</a></li>
								<li><a href="/admin/companies/approves">Aprovações pendentes</a></li>
							</ul>
						</li>

						<li>
							<a href="/admin/coupons"><i class="text-primary fa-solid fa-ticket"></i> Cupons</a>
							<ul>
								<li><a href="/admin/coupons">Todos os cupons</a></li>
								<li><a href="/admin/coupons/new">Novo cupom</a></li>
							</ul>
						</li>

						<li>
							<a href="javascript:void(0)"><i class="text-primary fa-solid fa-wallet"></i> Relatórios</a>
							<ul>
								<li><a href="/admin/reports/birthdays">Aniversários</a></li>
								<li><a href="/admin/reports/orders">Pedidos</a></li>
								<li><a href="/admin/reports/past-due-members">Membros Vencidos</a></li>
								<li><a href="/admin/reports/ranking">Ranking de Diamantes</a></li>
								<li><a href="/admin/members/export" download>Exportar Usuários</a></li>
							</ul>
						</li>
						
<!-- 
						<li>
							<a href=""></a>
						</li> -->

						<li>
							<a href="/admin/logout">Sair</a>
						</li>
					</ul>
				</nav>	


				
			</div>