<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?=$email_title?></title>
    <style>
        /* Reset styles for some clients */
        html, body{
            width: 100%;
            height: 100%;
        }
        body { margin: 0; padding: 0; height: 100%;}
        img { display: block; }
        table { border-collapse: collapse; }
    </style>
</head>
<body style="background-color:#ffffff; margin: 0; padding: 0;">
    <!-- Wrapper Table for Email Content -->
    <table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color:#ffffff;">
        <tr>
            <td align="center">
                <!-- Main Table -->
                <table width="600" border="0" cellspacing="0" cellpadding="0" style="background-color:#F5F5F5;">
                    <!-- Header Section -->
                    <tr>
                        <td align="center" style="padding: 20px 0;">
                            <img src="https://canalsaltoalto.com/assets/images/logo-csa.png" alt="Logotipo do Canal Salto Alto" height="50" style="display:block;">
                        </td>
                    </tr>
                    <!-- Main Content Section -->
                    <tr style="background-color: #F5F5F5">
                        <td style="padding: 20px; font-family: Arial, sans-serif; font-size: 16px; line-height: 1.5; color: #333;">
                            <?=$email_content?>
                        </td>
                    </tr>
                    <!-- Footer Section -->
                    <tr>
                        <td align="center" style="padding: 20px; background-color: #F5F5F5; color: #333; font-family: Arial, sans-serif; font-size: 14px;">
                            <p style="margin: 0;">&copy; 2025 Canal Salto Alto. Todos os Direitos Reservados.</p>
                            <p><small>Você está recebendo este e-mail porque é uma membro do Canal Salto Alto. Para remover seu e-mail da nossa lista, acesse sua conta e mude as preferências de comunicação.</small></p>
                            <!-- <p style="margin: 0;"><a href="https://example.com/unsubscribe" style="color: #ffffff; text-decoration: underline;">Unsubscribe</a></p> -->
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>
</html>
