		<footer id="footer" class="site__footer">
			<div class="container">
				<div class="row">
					<div class="col-md-4 mb-4">
						<a href="<?=PATH?>"><img src="<?=PATH?>assets/images/logo-csa.png" alt="Logotipo do Canal Salto Alto" class="site__footer--logo" /></a>
						<!-- <p class="mt-4">Uma rede de apoio a mulheres empreendedoras.</p> -->
					</div>
					<div class="col-md-4 mb-2">
						<h3>Navegação</h3>
						<ul>
							<li><a href="javascript:void(0)" onclick="document.documentElement.scrollTop = 0;">Voltar ao topo</a></li>
							<li><a href="<?=PATH?>seja-membro">Seja Membro</a></li>
							<li><a href="<?=PATH?>privacidade-e-dados">Política de Privacidade e LGPD</a></li>
							<li><a href="<?=PATH?>politica-de-bom-uso">Política de Bom Uso do Site e da Rede de Empreendedoras</a></li>
						</ul>
					</div>

					<div class="col-md-4 mb-2">
						<h3>Redes Sociais</h3>
						<ul class="site__footer--social d-flex">
							<li><a href="https://www.youtube.com/c/CanalSaltoAlto" target="_blank"><i class="fa-brands fa-youtube"></i></a></li>
							<li><a href="https://www.instagram.com/canalsaltoalto/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
							<li><a href="https://www.facebook.com/canalsaltoalto/" target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
							<li><a href="https://x.com/saltoaltocanal" target="_blank"><i class="fa-brands fa-x-twitter"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="container mt-4">
				<div class="row">
					<div class="col-md-6">
						&copy; Todos os direitos reservados ao Canal Salto Alto.
					</div>
					<div class="col-md-6 text-start text-md-end"><a href="https://gabrielcarvalho.digital/" target="_blank">Desenvolvido por Gabriel Carvalho</a></div>
				</div>
			</div>
		</footer>


		<a href="https://api.whatsapp.com/send?phone=5527996959895&text=Ol%C3%A1,%20vim%20pelo%20site"><img style="width: 65px;border-radius: 65px; position: fixed; bottom: 20px;right: 20px;" src="<?=PATH?>assets/images/whatsapp-icon.svg" alt="" /></a>