		<header class="app__header">
			<div class="container-xl">
				<div class="d-flex align-items-center justify-content-between">
					<div>
						<a href="<?=PATH?>app"><img src="<?=PATH?>assets/images/logo-csa-white.png" alt="Logotipo do Canal Salto Alto" class="app__header--logo" /></a>
					</div>
					<div>
						<nav class="d-none d-lg-flex">
							<ul class="d-flex">
								<li><a href="<?=PATH?>app/notices">Avisos</a></li>
								<li><a href="<?=PATH?>app/contents">Conteúdos</a></li>
								<li><a href="<?=PATH?>app/clubs">Clube</a></li>
								<li><a href="<?=PATH?>app/events">Eventos</a></li>
								<li><a href="<?=PATH?>app/publis">Divulgue Aqui</a></li>
								<li><a href="<?=PATH?>app/members">Membros</a></li>
								<li><a href="<?=PATH?>app/companies">Empresas</a></li>
							</ul>
							<ul class="app__header--social d-flex">
								<li><a href="https://www.youtube.com/c/CanalSaltoAlto" target="_blank"><i class="fa-brands fa-youtube"></i></a></li>
								<li><a href="https://www.instagram.com/canalsaltoalto/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
								<li><a href="https://www.facebook.com/canalsaltoalto/" target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
								<li><a href="https://twitter.com/saltoaltocanal" target="_blank"><i class="fa-brands fa-x-twitter"></i></a></li>
							</ul>
						</nav>
					</div>
					<div class="col-btns">
						<div class="d-none d-lg-flex flex-row align-items-center my-profile">
							<a href="/app/profile">
								<span>Meu Perfil</span>
								<img src="<?=PATH.((!isset(USER->profile_photo) OR empty(USER->profile_photo)) ? 'assets/images/profile-icon.png' : USER->profile_photo)  ?>" alt="" class="profile-icon" />
							</a>
							<!-- <ul class="my-profile__menu">
								<li><a href="/app/profile">Editar perfil</a></li>
								<li><a href="/app/logout">Sair</a></li>
							</ul> -->
						</div>

						<a href="javascript:void(0)" class="d-flex d-lg-none open-menu-btn" onclick="$('.lmenu').fadeIn(200)"><i class="fa-solid fa-bars"></i></a>
					</div>
				</div>
			</div>
			<nav class="lmenu">
				<div class="container-xl">
					<div class="lmenu--header row align-items-center justify-content-between">
						<div class="col-6">
							<img src="<?=PATH?>assets/images/logo-csa-white.png" alt="Logotipo do Canal Salto Alto" class="img-fluid" />
						</div>
						<div class="col-6 text-end">
							<a href="javascript:void(0)" class="close-menu p-0 d-block" onclick="$('.lmenu').fadeOut(200)"><i class="fa-solid fa-xmark"></i></a>
						</div>
					</div>

					<ul class="d-flex flex-column">
						<li><a href="<?=PATH?>app/notices">Avisos</a></li>
						<li><a href="<?=PATH?>app/contents">Conteúdos</a></li>
						<li><a href="<?=PATH?>app/clubs">Clube</a></li>
						<li><a href="<?=PATH?>app/events">Eventos</a></li>
						<li><a href="<?=PATH?>app/publis">Divulgue Aqui</a></li>
						<li><a href="<?=PATH?>app/members">Membros</a></li>
						<li><a href="<?=PATH?>app/companies">Empresas</a></li>
					</ul>
					<ul class="app__header--social d-flex">
						<li><a href="https://www.youtube.com/c/CanalSaltoAlto" target="_blank"><i class="fa-brands fa-youtube"></i></a></li>
						<li><a href="https://www.instagram.com/canalsaltoalto/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
						<li><a href="https://www.facebook.com/canalsaltoalto/" target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
						<li><a href="https://twitter.com/saltoaltocanal" target="_blank"><i class="fa-brands fa-x-twitter"></i></a></li>
					</ul>

					<div class="d-flex flex-row align-items-center my-profile">
						<a href="/app/profile">
							<span>Meu Perfil</span>
							<img src="<?=PATH.((!isset(USER->profile_photo) OR empty(USER->profile_photo)) ? 'assets/images/profile-icon.png' : USER->profile_photo)  ?>" alt="" class="profile-icon" />
						</a>
						<!-- <ul class="my-profile__menu">
							<li><a href="/app/profile">Editar perfil</a></li>
							<li><a href="/app/logout">Sair</a></li>
						</ul> -->
					</div>
				</div>
			</nav>
		</header>