        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="<?=PATH?>assets/css/styles.css?<?=uniqid()?>" />
        <link rel="icon" href="<?=PATH?>assets/images/favicon.png" />
        <meta name="msapplication-TileImage" content="<?=PATH?>assets/images/favicon-app.jpg" />

        <link rel="manifest" href="<?=PATH?>manifest.json"/>
        <meta name="mobile-web-app-capable" content="yes">
        <meta name="apple-mobile-web-app-status-bar-style" content="default">
        <meta name="apple-mobile-web-app-title" content="Canal Salto Alto">
        <link rel="apple-touch-icon" href="<?=PATH?>assets/images/icon-192x192.png">



        <script type="text/javascript">
            (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "ogp3wolm80");
        </script>
        <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-N5D77MV');</script>
        <!-- End Google Tag Manager -->


        <?php if(isset($is_private_area) && $is_private_area): ?>
            <script src="https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js" defer></script>
            <script>
            window.OneSignalDeferred = window.OneSignalDeferred || [];
            OneSignalDeferred.push(async function(OneSignal) {
                await OneSignal.init({
                appId: "fbd0925d-d9e9-4ad1-b628-29d2fdce12b7",
                safari_web_id: "web.onesignal.auto.313afc18-65a3-4cb5-bd8a-eabd69c6e4d8",
                notifyButton: {
                    enable: true,
                },
                });
            });
            </script>
        <?php endif; ?>