<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "ogp3wolm80");
</script>



        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="<?=PATH?>assets/css/styles.css?<?=uniqid()?>" />
        <link rel="icon" href="<?=PATH?>assets/images/favicon.png" />
        <link rel="apple-touch-icon" href="<?=PATH?>assets/images/favicon-app.jpg" />
        <meta name="msapplication-TileImage" content="<?=PATH?>assets/images/favicon-app.jpg" />


        <link rel="manifest" href="<?=PATH?>manifest.json"/>