<div class="members-list__item ranking animate__animated animate__faster animate__fadeInDown" style="animation-delay: 100ms ">
	<div class="members-list__item--header">
		<div class="d-flex flex-column flex-md-row align-items-center photo_title">
			<img src="/<?=(!empty($profile_photo)) ? $profile_photo : 'assets/images/default-pfp.png'?>" class="logo" alt=""/>
			<h3 class="mb-0"><?=$firstname." ".$lastname?></h3>
		</div>
        <div class="d-flex flex-row align-items-center btn-diamonds">
            <img src="<?=PATH?>assets/images/icon-diamond.svg" alt="" />
            <span><?=(intval($diamonds))?></span>
        </div>
	</div>
</div>