<div class="companies-list__item animate__animated animate__faster animate__fadeInDown">
	<div class="companies-list__item--image" style="background-image: url('/<?=$company_image?>')"></div>
	<div class="companies-list__item--content">
		<ul>

			<?php if(!empty($facebook_url)): ?>
			<li><a href="<?=$facebook_url?>" target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
			<?php endif; ?>

			<?php if(!empty($instagram_url)): ?>
				<li><a href="<?=$instagram_url?>" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
			<?php endif; ?>

			<?php if(!empty($site_url)): ?>
				<li><a href="<?=$site_url?>" target="_blank"><i class="fa-solid fa-link"></i></a></li>
			<?php endif; ?>
		</ul>
		<h3 class="mt-3"><?=$company_name?></h3>
		<div class="description"><?=$company_description?></div>
		<div class="d-flex flex-row align-items-center mt-2">
			<a href="https://wa.me/55<?=$cellphone?>" target="_blank"><button class="btn btn-rose btn-rounded"><i class="fa-brands fa-whatsapp"></i> <?=$cellphone?></button></a>
			<div class="d-flex flex-row p-2 align-items-center metas">
				<img src="/<?=(!empty($company['profile_photo'])) ? $profile_photo : 'assets/images/default-pfp.png'?>" style="width: 20px;height: 20px;border-radius: 20px;" alt=""/>
			<span class="p-2 d-block">by <?=$firstname." ".$lastname?></span>
			</div>
		</div>
	</div>
</div>