<div class="clubs-list__item animate__animated animate__faster animate__fadeInDown"  style="animation-delay: 200ms ">
			  			<div class="clubs-list__item--image" style="background-image: url('/<?=$club_image?>')"></div>
			  			<div class="clubs-list__item--content">
			  				<h3 class="mt-3"><?=$club_title?></h3>
			  				<div class="description"><?=$club_description?></div>
			  			</div>
			  		</div>