<header class="site__header">
			<div class="container">
				<div class="d-flex align-items-center justify-content-between">
					<div>
						<a href="<?=PATH?>"><img src="<?=PATH?>assets/images/logo-csa-white.png" alt="Logotipo do Canal Salto Alto" class="site__header--logo" /></a>
					</div>
					<div>
						<nav class="d-flex align-items-center">
							<ul class="d-flex">
								<li><a href="<?=PATH?>">Início</a></li>
								<li><a href="<?=PATH?>noticias">Notícias</a></li>
								<li><a href="<?=PATH?>seja-membro">Seja Membro</a></li>
								<li><a href="<?=PATH?>quem-somos">Quem Somos</a></li>
							</ul>
							<ul class="site__header--social d-flex">
								<li><a href="https://www.youtube.com/c/CanalSaltoAlto" target="_blank"><i class="fa-brands fa-youtube"></i></a></li>
								<li><a href="https://www.instagram.com/canalsaltoalto/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
								<li><a href="https://www.facebook.com/canalsaltoalto/" target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
								<li><a href="https://twitter.com/saltoaltocanal" target="_blank"><i class="fa-brands fa-x-twitter"></i></a></li>
							</ul>
							<div>
								<a href="/app/login"><button class="btn btn-rose btn-rounded">Faça login</button></a>
							</div>
						</nav>
					</div>
				</div>
			</div>
		</header>