<footer class="app__footer">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<img src="<?=PATH?>assets/images/logo-csa-white.png" alt="" class="app__footer--logo">
				<p class="mt-3">Uma rede de apoio a mulheres empreendedoras de todo o Brasil.</p>
			</div>

			<div class="col-md-4">
				<h3>Nos Encontre</h3>
				<div class="d-flex">
					
				</div>
				<ul class="app__footer--social d-flex">
					<li><a href="https://www.youtube.com/c/CanalSaltoAlto" target="_blank"><i class="fa-brands fa-youtube"></i></a></li>
					<li><a href="https://www.instagram.com/canalsaltoalto/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
					<li><a href="https://www.facebook.com/canalsaltoalto/" target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
					<li><a href="https://twitter.com/saltoaltocanal" target="_blank"><i class="fa-brands fa-x-twitter"></i></a></li>
				</ul>
			</div>
			<div class="col-md-4">
				<h3>Acesso rápido</h3>
				<ul>
					<li><a href="#">Início</a></li>
					<li><a href="#">Suporte</a></li>
					<li><a href="#">Termos de Uso</a></li>
				</ul>
			</div>
			
		</div>
	</div>
	<div class="container pt-4 pb-4">
		<div class="row">
			<div class="col-md-6">
				<span>&copy; Todos os direitos reservados ao Canal Salto Alto.</span>
			</div>
			<div class="col-md-6 text-end">
				<a href="https://gabcarvalhogama.com.br" target="_blank">Plataforma criada por Gab Carvalho Gama</a>
			</div>
		</div>
	</div>
</footer>