		<header class="app__header">
			<div class="container">
				<div class="d-flex align-items-center justify-content-between">
					<div>
						<a href="<?=PATH?>app"><img src="<?=PATH?>assets/images/logo-csa-white.png" alt="Logotipo do Canal Salto Alto" class="app__header--logo" /></a>
					</div>
					<div>
						<nav class="d-flex">
							<ul class="d-flex">
								<li><a href="<?=PATH?>app/notices">Avisos</a></li>
								<li><a href="<?=PATH?>app/contents">Conteúdos</a></li>
								<li><a href="<?=PATH?>app/clubs">Clube</a></li>
								<li><a href="<?=PATH?>app/events">Eventos</a></li>
								<li><a href="<?=PATH?>app/publis">Divulgue Aqui</a></li>
								<li><a href="<?=PATH?>app/members">Membros</a></li>
								<li><a href="<?=PATH?>app/companies">Empresas</a></li>
							</ul>
							<ul class="app__header--social d-flex">
								<li><a href="https://www.youtube.com/c/CanalSaltoAlto" target="_blank"><i class="fa-brands fa-youtube"></i></a></li>
								<li><a href="https://www.instagram.com/canalsaltoalto/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
								<li><a href="https://www.facebook.com/canalsaltoalto/" target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
								<li><a href="https://twitter.com/saltoaltocanal" target="_blank"><i class="fa-brands fa-x-twitter"></i></a></li>
							</ul>
						</nav>
					</div>
					<div>
						<div class="d-flex flex-row align-items-center my-profile">
							<a href="/app/profile">
								<span>Meu Perfil</span>
								<img src="<?=PATH.((!isset($user->profile_photo) OR empty($user->profile_photo)) ? 'assets/images/profile-icon.png' : $user->profile_photo)  ?>" alt="" class="profile-icon" />
							</a>
							<ul class="my-profile__menu">
								<li><a href="/app/profile">Editar perfil</a></li>
								<li><a href="/app/logout">Sair</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</header>